# Generated by Django 3.2.7 on 2021-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_heading',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
