# Generated by Django 3.2.7 on 2021-12-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_article_short_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='short_heading',
        ),
    ]
