# Generated by Django 3.2.7 on 2021-12-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_article_short_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
