# Generated by Django 3.2.7 on 2021-12-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
