# Generated by Django 3.2.7 on 2021-12-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('born', models.DateField()),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Batting_style', models.CharField(max_length=100)),
                ('Bowling_style', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('matches', models.IntegerField()),
                ('batting_innings', models.IntegerField()),
                ('Bowling_innings', models.IntegerField()),
                ('No', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('highest', models.IntegerField()),
                ('bat_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BF', models.IntegerField()),
                ('bat_SR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hundred', models.IntegerField()),
                ('fifty', models.IntegerField()),
                ('double_hundred', models.IntegerField()),
                ('four', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('Ball_bowled', models.IntegerField()),
                ('runs_conceded', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('BBI', models.CharField(max_length=10)),
                ('BBM', models.CharField(max_length=40)),
                ('bowl_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bowl_SR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('economy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('five_wicket', models.IntegerField()),
                ('ten_wicket', models.IntegerField()),
                ('teams_played', models.CharField(max_length=100)),
                ('icc_bowling', models.IntegerField()),
                ('icc_batting', models.IntegerField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.nation')),
            ],
        ),
    ]
