# Generated by Django 3.2.7 on 2021-12-25 08:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='BF',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='Ball_bowled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='Bowling_innings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='No',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='bat_SR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='bat_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_innings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowl_SR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowl_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='double_hundred',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='economy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='fifty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='five_wicket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='four',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='highest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='hundred',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='icc_batting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='icc_bowling',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='runs_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ten_wicket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
    ]
