# Generated by Django 3.2.7 on 2021-12-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20211225_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessBoard',
        ),
    ]
