# Generated by Django 3.2.7 on 2021-12-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20211225_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_one_five_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp1_extras',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp1_total_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp1_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp2_extras',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp2_total_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp2_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_five_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_five_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_five_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_five_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_five_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_five_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_five_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_five_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_four_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_three_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_threeeco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_BF',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_NO',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_eco',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_overs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_runs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_runs_conc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_six',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_sr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two_wicket',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
