# Generated by Django 3.2.7 on 2021-12-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_remove_match_toss_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Toss',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.nation'),
        ),
    ]
