# Generated by Django 3.2.7 on 2021-12-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_alter_match_toss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='Toss',
        ),
    ]
