# Generated by Django 3.2.7 on 2021-12-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_remove_match_toss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_one_five',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='requests_created7', to='blogs.player'),
        ),
    ]
