# Generated by Django 3.2.7 on 2021-12-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_alter_match_player_one_five'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Toss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.nation'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created4', to='blogs.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created1', to='blogs.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created3', to='blogs.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created2', to='blogs.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created8', to='blogs.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created5', to='blogs.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created6', to='blogs.player'),
        ),
    ]
