# Generated by Django 3.2.7 on 2021-12-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.TextField(default='', null=True),
        ),
    ]
