# Generated by Django 3.2.7 on 2021-12-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actual_Run', models.IntegerField()),
                ('Bowler_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three', to='blogs.player')),
                ('Run_on_ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.run')),
                ('Runner_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='blogs.player')),
                ('Strike_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='blogs.player')),
            ],
        ),
    ]
