# Generated by Django 3.2.7 on 2021-12-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='Over',
            field=models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=2),
        ),
        migrations.AlterField(
            model_name='ball',
            name='Actual_Run',
            field=models.IntegerField(null=True),
        ),
    ]
