# Generated by Django 3.2.7 on 2021-12-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_auto_20211227_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='Actual_Run',
            field=models.IntegerField(default=0),
        ),
    ]
