# Generated by Django 3.2.7 on 2021-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0031_auto_20211227_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_match',
            name='Match',
            field=models.IntegerField(default=0),
        ),
    ]
