# Generated by Django 3.2.7 on 2021-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_alter_player_match_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='Run_on_ball',
            field=models.CharField(default='', max_length=10),
        ),
    ]
