# Generated by Django 3.2.7 on 2021-12-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0033_alter_ball_run_on_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_match',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.player'),
        ),
    ]
