# Generated by Django 3.2.7 on 2021-12-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0034_alter_player_match_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_match',
            name='Match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.match'),
        ),
    ]
