# Generated by Django 3.2.7 on 2021-12-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_alter_player_match_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_match',
            name='SR',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
