# Generated by Django 3.2.7 on 2021-12-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0036_alter_player_match_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='Run_on_ball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.run'),
        ),
    ]
