# Generated by Django 3.2.7 on 2021-12-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0037_alter_ball_run_on_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='Run_on_ball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='blogs.run'),
        ),
    ]
