# Generated by Django 3.2.7 on 2021-12-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0038_alter_ball_run_on_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
