# Generated by Django 3.2.7 on 2021-12-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0040_auto_20211228_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_match',
            name='SR',
        ),
    ]
