# Generated by Django 3.2.7 on 2021-12-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0041_remove_player_match_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_match',
            name='Economy',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
