# Generated by Django 3.2.7 on 2021-12-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0043_player_match_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='Over',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
