# Generated by Django 3.2.7 on 2021-12-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0045_alter_ball_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
