# Generated by Django 3.2.7 on 2021-12-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0046_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_match',
            name='over1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
