# Generated by Django 3.2.7 on 2021-12-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0047_player_match_over1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_match',
            name='over',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player_match',
            name='over1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
