# Generated by Django 3.2.7 on 2021-12-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_auto_20211229_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
