# Generated by Django 3.2.7 on 2021-12-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0049_match_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='Over',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
