# Generated by Django 3.2.7 on 2021-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0050_alter_ball_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opp1_overs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp2_overs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
