# Generated by Django 3.2.7 on 2021-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0051_auto_20211230_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_match',
            name='bat_position',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player_match',
            name='status',
            field=models.CharField(default='Yet to bat', max_length=100),
        ),
    ]
