# Generated by Django 3.2.7 on 2021-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0052_auto_20211230_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='real_comm',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='run',
            name='comm',
            field=models.CharField(default='', max_length=100),
        ),
    ]
